// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

/*
Package raftpb is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	LastVoted
	RequestVoteReq
	RequestVoteResp
	LogEntry
	AppendEntriesReq
	AppendEntriesResp
*/
package raftpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogEntry_LogType int32

const (
	LogEntry_LogCommand LogEntry_LogType = 0
	LogEntry_LogNoop    LogEntry_LogType = 1
)

var LogEntry_LogType_name = map[int32]string{
	0: "LogCommand",
	1: "LogNoop",
}
var LogEntry_LogType_value = map[string]int32{
	"LogCommand": 0,
	"LogNoop":    1,
}

func (x LogEntry_LogType) String() string {
	return proto.EnumName(LogEntry_LogType_name, int32(x))
}
func (LogEntry_LogType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type LastVoted struct {
	VotedFor  string `protobuf:"bytes,1,opt,name=votedFor" json:"votedFor,omitempty"`
	VotedTerm uint64 `protobuf:"varint,2,opt,name=votedTerm" json:"votedTerm,omitempty"`
}

func (m *LastVoted) Reset()                    { *m = LastVoted{} }
func (m *LastVoted) String() string            { return proto.CompactTextString(m) }
func (*LastVoted) ProtoMessage()               {}
func (*LastVoted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LastVoted) GetVotedFor() string {
	if m != nil {
		return m.VotedFor
	}
	return ""
}

func (m *LastVoted) GetVotedTerm() uint64 {
	if m != nil {
		return m.VotedTerm
	}
	return 0
}

type RequestVoteReq struct {
	Term         uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LastLogIndex uint64 `protobuf:"varint,2,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm  uint64 `protobuf:"varint,3,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
	CandidateID  string `protobuf:"bytes,4,opt,name=candidateID" json:"candidateID,omitempty"`
}

func (m *RequestVoteReq) Reset()                    { *m = RequestVoteReq{} }
func (m *RequestVoteReq) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteReq) ProtoMessage()               {}
func (*RequestVoteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestVoteReq) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *RequestVoteReq) GetCandidateID() string {
	if m != nil {
		return m.CandidateID
	}
	return ""
}

type RequestVoteResp struct {
	Term        uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool   `protobuf:"varint,2,opt,name=voteGranted" json:"voteGranted,omitempty"`
}

func (m *RequestVoteResp) Reset()                    { *m = RequestVoteResp{} }
func (m *RequestVoteResp) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResp) ProtoMessage()               {}
func (*RequestVoteResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestVoteResp) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResp) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type LogEntry struct {
	Term    uint64           `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Index   uint64           `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Data    []byte           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	LogType LogEntry_LogType `protobuf:"varint,4,opt,name=logType,enum=raftpb.LogEntry_LogType" json:"logType,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogEntry) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LogEntry) GetLogType() LogEntry_LogType {
	if m != nil {
		return m.LogType
	}
	return LogEntry_LogCommand
}

type AppendEntriesReq struct {
	Term              uint64      `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderID          string      `protobuf:"bytes,2,opt,name=leaderID" json:"leaderID,omitempty"`
	PrevLogIndex      uint64      `protobuf:"varint,3,opt,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevLogTerm       uint64      `protobuf:"varint,4,opt,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	LeaderCommitIndex uint64      `protobuf:"varint,6,opt,name=leaderCommitIndex" json:"leaderCommitIndex,omitempty"`
	Entries           []*LogEntry `protobuf:"bytes,5,rep,name=entries" json:"entries,omitempty"`
}

func (m *AppendEntriesReq) Reset()                    { *m = AppendEntriesReq{} }
func (m *AppendEntriesReq) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesReq) ProtoMessage()               {}
func (*AppendEntriesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AppendEntriesReq) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReq) GetLeaderID() string {
	if m != nil {
		return m.LeaderID
	}
	return ""
}

func (m *AppendEntriesReq) GetPrevLogIndex() uint64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesReq) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesReq) GetLeaderCommitIndex() uint64 {
	if m != nil {
		return m.LeaderCommitIndex
	}
	return 0
}

func (m *AppendEntriesReq) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResp struct {
	Term         uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success      bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	LastLogIndex uint64 `protobuf:"varint,3,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
}

func (m *AppendEntriesResp) Reset()                    { *m = AppendEntriesResp{} }
func (m *AppendEntriesResp) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResp) ProtoMessage()               {}
func (*AppendEntriesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AppendEntriesResp) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesResp) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*LastVoted)(nil), "raftpb.LastVoted")
	proto.RegisterType((*RequestVoteReq)(nil), "raftpb.RequestVoteReq")
	proto.RegisterType((*RequestVoteResp)(nil), "raftpb.RequestVoteResp")
	proto.RegisterType((*LogEntry)(nil), "raftpb.LogEntry")
	proto.RegisterType((*AppendEntriesReq)(nil), "raftpb.AppendEntriesReq")
	proto.RegisterType((*AppendEntriesResp)(nil), "raftpb.AppendEntriesResp")
	proto.RegisterEnum("raftpb.LogEntry_LogType", LogEntry_LogType_name, LogEntry_LogType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RaftService service

type RaftServiceClient interface {
	RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteResp, error)
	AppendEntries(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesResp, error)
}

type raftServiceClient struct {
	cc *grpc.ClientConn
}

func NewRaftServiceClient(cc *grpc.ClientConn) RaftServiceClient {
	return &raftServiceClient{cc}
}

func (c *raftServiceClient) RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteResp, error) {
	out := new(RequestVoteResp)
	err := grpc.Invoke(ctx, "/raftpb.RaftService/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftServiceClient) AppendEntries(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesResp, error) {
	out := new(AppendEntriesResp)
	err := grpc.Invoke(ctx, "/raftpb.RaftService/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RaftService service

type RaftServiceServer interface {
	RequestVote(context.Context, *RequestVoteReq) (*RequestVoteResp, error)
	AppendEntries(context.Context, *AppendEntriesReq) (*AppendEntriesResp, error)
}

func RegisterRaftServiceServer(s *grpc.Server, srv RaftServiceServer) {
	s.RegisterService(&_RaftService_serviceDesc, srv)
}

func _RaftService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftpb.RaftService/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServiceServer).RequestVote(ctx, req.(*RequestVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftService_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServiceServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftpb.RaftService/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServiceServer).AppendEntries(ctx, req.(*AppendEntriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raftpb.RaftService",
	HandlerType: (*RaftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _RaftService_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _RaftService_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0xb4, 0xdb, 0x8f, 0xc9, 0x52, 0xba, 0x23, 0x04, 0xa1, 0xe2, 0x10, 0xe5, 0x80, 0x2a,
	0x84, 0x7a, 0x28, 0x77, 0x24, 0x44, 0x97, 0x55, 0xa5, 0x8a, 0x83, 0x59, 0x71, 0xf7, 0xd6, 0xb3,
	0x55, 0xa4, 0x36, 0xf6, 0xda, 0xde, 0x8a, 0xfe, 0x07, 0x6e, 0xfc, 0x05, 0x7e, 0x19, 0xbf, 0x04,
	0xd9, 0x49, 0xba, 0x49, 0x3f, 0x6e, 0x33, 0x6f, 0x9e, 0x5e, 0x9e, 0xe7, 0x4d, 0x00, 0x8c, 0xb8,
	0x77, 0x13, 0x6d, 0x94, 0x53, 0xd8, 0xf1, 0xb5, 0xbe, 0x4b, 0xaf, 0xa1, 0xbf, 0x10, 0xd6, 0xfd,
	0x54, 0x8e, 0x24, 0x8e, 0xa0, 0xb7, 0xf5, 0xc5, 0x37, 0x65, 0x62, 0x96, 0xb0, 0x71, 0x9f, 0xef,
	0x7b, 0x7c, 0x07, 0xfd, 0x50, 0xdf, 0x92, 0xd9, 0xc4, 0xcf, 0x13, 0x36, 0x6e, 0xf3, 0x27, 0x20,
	0xfd, 0xcd, 0x60, 0xc0, 0xe9, 0xe1, 0x91, 0x0a, 0x29, 0x4e, 0x0f, 0x88, 0xd0, 0x76, 0x9e, 0xcb,
	0x02, 0x37, 0xd4, 0x98, 0xc2, 0xe5, 0x5a, 0x58, 0xb7, 0x50, 0xab, 0x79, 0x2e, 0xe9, 0x57, 0xa9,
	0xd3, 0xc0, 0x30, 0x81, 0xa8, 0xec, 0xc3, 0xa7, 0x5a, 0x81, 0x52, 0x87, 0x3c, 0x63, 0x29, 0x72,
	0x99, 0x49, 0xe1, 0x68, 0x3e, 0x8b, 0xdb, 0xc1, 0x69, 0x1d, 0x4a, 0x6f, 0xe0, 0x65, 0xc3, 0x8d,
	0xd5, 0x27, 0xed, 0x24, 0x10, 0xf9, 0x27, 0xdc, 0x18, 0x91, 0x3b, 0x92, 0xc1, 0x4d, 0x8f, 0xd7,
	0xa1, 0xf4, 0x2f, 0x83, 0xde, 0x42, 0xad, 0xae, 0x73, 0x67, 0x76, 0x27, 0x25, 0x5e, 0xc1, 0x45,
	0x56, 0x7b, 0x4a, 0xd1, 0x78, 0xa6, 0x14, 0x4e, 0x04, 0xf3, 0x97, 0x3c, 0xd4, 0x38, 0x85, 0xee,
	0x5a, 0xad, 0x6e, 0x77, 0x9a, 0x82, 0xe3, 0xc1, 0x34, 0x9e, 0x14, 0x19, 0x4c, 0xaa, 0x0f, 0xf8,
	0xc2, 0xcf, 0x79, 0x45, 0x4c, 0xdf, 0x43, 0xb7, 0xc4, 0x70, 0x00, 0xb0, 0x50, 0xab, 0xaf, 0x6a,
	0xb3, 0x11, 0xb9, 0x1c, 0x3e, 0xc3, 0x28, 0x8c, 0xbe, 0x2b, 0xa5, 0x87, 0x2c, 0xfd, 0xc7, 0x60,
	0xf8, 0x45, 0x6b, 0xca, 0xa5, 0x17, 0xca, 0xc8, 0x9e, 0x0b, 0x60, 0x04, 0xbd, 0x35, 0x09, 0x49,
	0x66, 0x3e, 0x0b, 0x8e, 0xfb, 0x7c, 0xdf, 0xfb, 0x70, 0xb4, 0xa1, 0xed, 0x3e, 0x9c, 0x62, 0xf3,
	0x0d, 0xcc, 0x6f, 0xac, 0xec, 0x43, 0x38, 0xed, 0x22, 0x9c, 0x1a, 0x84, 0x1f, 0xe1, 0xaa, 0x50,
	0xf4, 0x56, 0x33, 0x57, 0x48, 0x75, 0x02, 0xef, 0x78, 0x80, 0x1f, 0xa0, 0x4b, 0x85, 0xe3, 0xf8,
	0x22, 0x69, 0x8d, 0xa3, 0xe9, 0xf0, 0x70, 0x29, 0xbc, 0x22, 0xa4, 0x04, 0x57, 0x07, 0x6f, 0x3c,
	0x13, 0x6b, 0x0c, 0x5d, 0xfb, 0xb8, 0x5c, 0x92, 0xb5, 0x65, 0xa4, 0x55, 0x7b, 0x74, 0x7f, 0xad,
	0xe3, 0xfb, 0x9b, 0xfe, 0x61, 0x10, 0x71, 0x71, 0xef, 0x7e, 0x90, 0xd9, 0x66, 0x4b, 0xc2, 0xcf,
	0x10, 0xd5, 0x6e, 0x09, 0x5f, 0x57, 0x06, 0x9b, 0xe7, 0x3e, 0x7a, 0x73, 0x12, 0xb7, 0x1a, 0x67,
	0xf0, 0xa2, 0x61, 0x1b, 0xf7, 0xb9, 0x1f, 0x26, 0x36, 0x7a, 0x7b, 0x66, 0x62, 0xf5, 0x5d, 0x27,
	0xfc, 0xb6, 0x9f, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0xba, 0x85, 0x0b, 0x2b, 0xc4, 0x03, 0x00,
	0x00,
}
