// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

/*
Package examplepb is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	KV
*/
package examplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KV_OpType int32

const (
	KV_OpPut    KV_OpType = 0
	KV_OpDelete KV_OpType = 1
)

var KV_OpType_name = map[int32]string{
	0: "OpPut",
	1: "OpDelete",
}
var KV_OpType_value = map[string]int32{
	"OpPut":    0,
	"OpDelete": 1,
}

func (x KV_OpType) String() string {
	return proto.EnumName(KV_OpType_name, int32(x))
}
func (KV_OpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type KV struct {
	Key    string    `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value  string    `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	OpType KV_OpType `protobuf:"varint,3,opt,name=opType,enum=examplepb.KV_OpType" json:"opType,omitempty"`
}

func (m *KV) Reset()                    { *m = KV{} }
func (m *KV) String() string            { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()               {}
func (*KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *KV) GetOpType() KV_OpType {
	if m != nil {
		return m.OpType
	}
	return KV_OpPut
}

func init() {
	proto.RegisterType((*KV)(nil), "examplepb.KV")
	proto.RegisterEnum("examplepb.KV_OpType", KV_OpType_name, KV_OpType_value)
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x72, 0x0b, 0x92, 0x94,
	0x6a, 0xb9, 0x98, 0xbc, 0xc3, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26,
	0xb0, 0x18, 0x84, 0x23, 0xa4, 0xc3, 0xc5, 0x96, 0x5f, 0x10, 0x52, 0x59, 0x90, 0x2a, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xa2, 0x07, 0x37, 0x49, 0xcf, 0x3b, 0x4c, 0xcf, 0x1f, 0x2c, 0x17,
	0x04, 0x55, 0xa3, 0xa4, 0xc8, 0xc5, 0x06, 0x11, 0x11, 0xe2, 0xe4, 0x62, 0xf5, 0x2f, 0x08, 0x28,
	0x2d, 0x11, 0x60, 0x10, 0xe2, 0xe1, 0xe2, 0xf0, 0x2f, 0x70, 0x49, 0xcd, 0x49, 0x2d, 0x49, 0x15,
	0x60, 0x4c, 0x62, 0x03, 0x3b, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x25, 0xc9, 0x47, 0x79,
	0xa1, 0x00, 0x00, 0x00,
}
